// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fksnxdqvzeiprosbisbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrc254ZHF2emVpcHJvc2Jpc2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzExNTIsImV4cCI6MjA2Mzg0NzE1Mn0.hFuAiYHAufVU-g86tVcKGBb7TpZdemva503WOm8OnoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);